### PR TITLE
Load Company Face From CompanyName

### LINKED ISSUE #2103: Change Company Owner not changing faces
**Version information:**
 - Platform: Windows 10
 - Version: 23.08

**Describe the bug**
You are meant to be able to change the company face by typing in a company owner name that matches a different face. E.g. "Agnes Armchair" should load the Agnes Armchair face.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open boulder breakers.
2. If the company owner face is Agnes Armchair change it to something else.
3. Enter a company owner name of "Agnes Armchair"

**Expected behaviour**
Company face is changed to Agnes Armchair

Easily fixed by adding 
`memcpy((char*)0x009C646E, renameStringBuffer, sizeof(renameStringBuffer));` to before https://github.com/OpenLoco/OpenLoco/blob/5142f74de64291dc5a5cfefc13890ca4cc3e3e05/src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp#L100

This is because the sub_434BA1 is the function that handles this feature and it expects the global var 0x009C646E to hold the new company owner name.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
This was meant to fix #2103 but i accidentally merged a temp fix for that issue during making the 23.08.1 release.

### CODE REVIEW

File: src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp [hunk 1]
```diff
@@ -108,8 +110,79 @@ namespace OpenLoco::GameCommands
...
+                        const uint16_t unkRhs = *reinterpret_cast<const uint16_t*>(rhs);
+                        if (unkLhs != unkRhs)
+                        {
+                            return false;
+                        }
+                        lhs += 2;
+                        rhs += 2;
+                        continue;
+                    }
+                    auto toLower = [](const char chr) -> char {
```
Comment (duncanspumpkin) [inline src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp:153]: Yeah i know i could have used std::tolower...

Comment (AaronVanGeffen) [reply src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp]: Any particular reason not to? (or std::toupper, for that matter)

Comment (duncanspumpkin) [reply src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp]: because of it being a locale function and all the headaches involved with locale.

File: src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp [hunk 2]
```diff
@@ -108,8 +110,79 @@ namespace OpenLoco::GameCommands
...
+            // Copy the string as it needs some processing
+            std::string objectName = object.second._name;
+            // Not sure what ControlCodes::pop16 is doing in the object name but it is at the start of all the object names
+            objectName.erase(std::remove(std::begin(objectName), std::end(objectName), ControlCodes::pop16));
+
+            auto strcmpSpecial = [](const char* lhs, const char* rhs) {
+                while (*lhs && *rhs)
+                {
+                    const auto chr = *lhs;
+                    if (chr == '\xFF')
```
Comment (duncanspumpkin) [inline src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp:135]: This is interesting in that this is clearly some sort of control code but it isn't a valid one for drawing. So its all dead code. Mysterious...

Comment (AaronVanGeffen) [reply src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp:135]: Guessing this could be related to handling multibyte characters? Not active in the English version, but it wouldn't be the first remnant either.

Comment (duncanspumpkin) [reply src/OpenLoco/src/GameCommands/Company/RenameCompanyOwner.cpp:135]: If so it's a very odd multibyte format.

**Review by LeftofZen — APPROVED** [review]
playtested, everything seems the same as current 23.08.1. note there is actually a bug in how the object selection window displays company faces (it shows a small preview and doesn't draw the image to size), but that isn't caused by this PR
