### PR TITLE
Fix #2678. Train bogie body draw order and body bound box

### LINKED ISSUE #2678: Vehicle clipping compared with original game
**Version information:**
 - Platform: Windows 10
 - Version: 24.10

**Describe the bug**
Some of my custom made objects have a clipping issue in OpenLoco that doesn't exist in the original game.

**To Reproduce**
I can send you the custom object if needed to test.

**Expected behaviour**
The custom made object is rendered correctly without the clipping issue.

Image

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Mistake from #2513 caused the vehicle paint to have wrong bound boxes and a change from implementing the vehicle draw inline caused bogies which overlap other bodies to change ordering.

Possible source of 1st bug of #2540

### CODE REVIEW

**Review by LeftofZen — COMMENTED** [review]
I don't see any issues like in #2678, with the objects provided in that issue.

I do see this 'glitch'. The front of the train is clipped out. its on a pure vertical line in the centre of the tile. I'm not sure if this is the original issue or its just an issue with oversized sprites:
image

Same issue on the opposing corner
image

**Comment by LeftofZen** [comment]
I do also see the bottom of the front vehicle clipping still
image

**Review by LeftofZen — COMMENTED** [review]
Bogies in the inline-sprite view are also still off

image

File: src/OpenLoco/src/Paint/PaintVehicle.cpp [hunk 1]
```diff
@@ -222,7 +222,7 @@ namespace OpenLoco::Paint
                 offsetModifier = -offsetModifier;
             }
 
-            const auto unk1 = Math::Trigonometry::computeXYVector(offsetModifier, originalYaw) / 2;
+            const auto unk1 = Math::Trigonometry::computeXYVector(offsetModifier, originalYaw) / 8;
```
Comment (LeftofZen) [inline src/OpenLoco/src/Paint/PaintVehicle.cpp:225]: can we give unk1 a name

**Comment by duncanspumpkin** [comment]
> Bogies in the inline-sprite view are also still off
> 
> image

Okay fixed the build window as well. (It used a slightly special bit of code so had to apply the fix yet again)

**Review by AaronVanGeffen — APPROVED** [review]
