### PR TITLE
Fix title screen music not playing after switching audio device

### LINKED ISSUE #2689: Title screen music doesn't start playing again if you switch sound device
**Version information:**
 - Platform: Windows 10
 - Version: 24.10
 - Build/commit: 52acc01f

**Describe the bug**
When you change audio device in the options, the title screen music stops, and doesn't resume until after you either go into a game or restart OpenLoco.

This bug can confuse players into thinking they need to restart the game to fix the game's audio, but evidentially the audio is otherwise still working completely fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open game to the title screen.
2. Click "Options" in the top-right, and navigate to the Sound tab.
3. Ensure that "Play title screen music" is checked and that you can hear the music.
4. Open the drop down, and make a selection. (This bug happens even if you selecting the same option that was already selected).
5. Notice that the music has now stopped. Wait for a vehicle to be on screen and listen out for vehicle noises to confirm that the game is still capable of playing audio.

**Expected behaviour**
The title screen music restarting from the beginning. (Or idealistically, just continue playing from where it was)

**Further details**
- After reproducing the bug, notice that if you uncheck "Play title screen music", and then check it again, the music continues to not play.
- The title screen music comes back if you load into a saved or new game, and then quit to menu to re-open the title screen. This is apparently not the case for the Scenario Editor though.
- This bug doesn't happen if you always had "Play title screen music" unchecked when you select a sound device (but doing so after the bug has already happened doesn't fix the music).

**Additional context**
- Could not reproduce in the original Locomotion, as I could not find its options menu on its title screen.
- Probably unrelated to #2667, as the title screen music **does** restart playing (i.e. loop) after it finishes the normal way, and my fix for 2667 doesn't resolve this issue.

### PR DESCRIPTION
**Pull request by LeeSpork**
Fixes #2689.

To do:
- [X] Add changelog entry
    - [X] Wait for 2750 to be merged so the changelog doesn't lie

### CODE REVIEW

File: src/OpenLoco/src/Audio/Audio.cpp [hunk 1]
```diff
@@ -184,6 +184,16 @@ namespace OpenLoco::Audio
...
+
+        // Resume title music if it should be playing
+        if (isTitleMode())
+        {
+            auto& cfg = Config::get();
+            if (cfg.audio.playTitleMusic)
+            {
+                Audio::playMusic(Environment::PathId::css5, Config::get().old.volume, true);
+            }
+        }
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Audio/Audio.cpp:196]: This `reinitialise` function is only called from `Audio::setDevice`, which is only called by the option window. I'd prefer we handle the music logic there instead.

Comment (LeeSpork) [reply src/OpenLoco/src/Audio/Audio.cpp:196]: I did it this way because making sure that the music is in the correct state felt more like a 'reinitialise audio' thing than a 'set audio device' thing to me, but I'm happy to change it if no one agrees or I'm outvoted

Comment (AaronVanGeffen) [reply src/OpenLoco/src/Audio/Audio.cpp:196]: Yeah, I can see why you did it this way. Ideally, the Audio subsystem doesn't have to deal with game-specific logic. That way, it could be easily re-used by other projects in the future. @ZehMatt Do you agree?

**Review by AaronVanGeffen — COMMENTED** [review]
I've rebased the PR. Code-wise, it looks good to me, but I don't have multiple audio devices to switch between.

@LeeSpork, I'm assuming you've tested this to work for you?

**Comment by LeeSpork** [comment]
IIRC you don't even need to switch between different audio devices, you can just re-select the one you were already using

**Comment by LeeSpork** [comment]
I'm sure I would have, but can test tomorrow to make sure if needed (with two audio devices)

**Comment by AaronVanGeffen** [comment]
Turns out Wine exposes macOS's audio output devices as multiple devices as well, so I can test this locally as well.

**Review by AaronVanGeffen — APPROVED** [review]
