### PR TITLE
Fix ghost vehicles staying placed down when placement is interrupted

### LINKED ISSUE #2526: Ghost vehicles stay placed down when placement is interrupted
**Version information:**
 - Platform: macOS
 - Version: 24.06+
 - Build/commit: 9705ace8148959d51acc20e331be5ab6672d994e

An oddity I noticed while testing vehicle placement for #2508 is that **ghost** vehicles stay placed down when closing the vehicle window for the vehicle being placed. I was surprised to find this also occurs on current master, but seems like the wrong behaviour to me.

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Fixes #2526.

### CODE REVIEW

File: src/OpenLoco/src/Windows/Vehicle.cpp [hunk 1]
```diff
@@ -1048,6 +1048,15 @@ namespace OpenLoco::Ui::Windows::Vehicle
             return self;
         }
 
+        // ???
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Windows/Vehicle.cpp:1051]: I believe this function was missing. Need to check if it was there originally, and add the address if so.

Comment (duncanspumpkin) [reply src/OpenLoco/src/Windows/Vehicle.cpp:1051]: Looks like it wasn't in original. Also we need this for the main tab.

**Review by duncanspumpkin — APPROVED** [review]
