### PR TITLE
Fix #1676, #1702. Scenario list crash/hang on new scenarios

### LINKED ISSUE #1676: Crash - creating new scenario with pre-existing scenario landscape
**Version information:**
 - Platform: Windows 10
 - Version: 22.10
 - Build/commit: 68882c9

**Describe the bug**
When you create a new scenario by loading a previous landscape, then save it with the same name as a _completed_ scenario, the game hangs and sometimes crashes when you attempt to start a new game from the "New Game" menu.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to "Create Scenario"
2. "Load Landscape"
3. Pick any landscape (but especially a landscape that is part of a completed scenario)
4. Save as a new scenario (does not matter what you name it, it will show up with the same name as the completed scenario and there will be 2 of them)
5. Attempt to play the scenario - attempt to hover over the scenario, game will become unresponsive

ALTERNATIVELY - I am not sure which of these caused the initial issue
1. Go to "Create Scenario"
2. "Load Landscape"
3. Folder up to load a scenario into the landscape editor, rather than a landscape (especially a completed scenario)
4. Save as a new scenario (does not matter what you name it, it will show up with the same name as the completed scenario and there will be 2 of them)
5. Attempt to play the scenario - attempt to hover over the scenario, game will become unresponsive

**Expected behaviour**
Be able to hover over and select new scenario

**Additional context**
I tried to find the folder where custom saved scenarios are to delete them, but I can't find it in either Roaming - openloco - save OR in programfilesx86 - atari - locomotion. If you can point me to where that is, then I can try that.

EDIT - okay now I can't create any scenario from a saved landscape no matter what. I think by creating a custom scenario by loading an old scenario, it corrupted whatever file system is used to make new scenarios.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Mistake made in implementation of the editorcontroller meant that invalid currency objects were set as the currency of a scenario meta details. This would cause the game to unload the currency object which would change the layout of image data set for water object which would cause invalid offsets to be set in the palette table which would cause the image draw functions to behave oddly causing crashs or infinite loops.

### CODE REVIEW

File: src/OpenLoco/src/Windows/ScenarioSelect.cpp [hunk 1]
```diff
@@ -481,8 +497,12 @@ namespace OpenLoco::Ui::Windows::ScenarioSelect
...
             return;
 
-        self.info = reinterpret_cast<uintptr_t>(scenarioEntry);
-        self.invalidate();
+        if (self.info != reinterpret_cast<uintptr_t>(scenarioEntry))
+        {
+            self.info = reinterpret_cast<uintptr_t>(scenarioEntry);
+            self.invalidate();
+            _warnOnce = false;
+        }
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Windows/ScenarioSelect.cpp:505]: This could have caused a slowdown, right? Perhaps this could be the cause of #1021? I've had trouble reproducing it, but this diff reminded me of that issue.

Comment (duncanspumpkin) [reply src/OpenLoco/src/Windows/ScenarioSelect.cpp:505]: I'm not sure the load screen uses this. Could be wrong but think it's only scenario select

Comment (AaronVanGeffen) [reply src/OpenLoco/src/Windows/ScenarioSelect.cpp:505]: Ahh no you're right, I'm mixing things up.

**Review by AaronVanGeffen — APPROVED** [review]
Could you add a changelog entry? LGTM otherwise
