### PR TITLE
Fix underflow in number of towns in scenario editor

### LINKED ISSUE #1430: No lower limit on towns in scenario editor landscape generator
**Version information:**
 - Platform: Win11
 - Version: e.g. 22.03.1
 - Build/commit: e.g. 0c4cc36

**Describe the bug**
In scenario editor the `-` stepper for `No. of towns` is unbounded on decrement.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Scenario Editor
2. Go to Landscape Generation window
3. Go to Towns tab
4. Click `-` (decrement) stepper past 0 and see it wrap to 255
5. Trying to `+` (increment) resets the limit to 80.

**Expected behaviour**
Decrement operation stops at 1

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by LeftofZen**
fixes #1430

### CODE REVIEW

File: src/OpenLoco/Windows/LandscapeGeneration.cpp [hunk 1]
```diff
@@ -1049,7 +1049,7 @@ namespace OpenLoco::Ui::Windows::LandscapeGeneration
 
                 case widx::number_of_towns_down:
                 {
-                    uint16_t newNumTowns = std::max<uint16_t>(0, options.numberOfTowns - 1);
+                    uint16_t newNumTowns = std::max<uint16_t>(1, options.numberOfTowns - 1);
```
Comment (duncanspumpkin) [inline src/OpenLoco/Windows/LandscapeGeneration.cpp:1052]: Could perhaps make this a constant defined in the town manager

Comment (LeftofZen) [reply src/OpenLoco/Windows/LandscapeGeneration.cpp:1052]: `kMaxTowns` is defined in `S5::Limits`, so it makes sense to me to put `kMinTowns` in the same spot, what do you think?

Comment (duncanspumpkin) [reply src/OpenLoco/Windows/LandscapeGeneration.cpp]: sure

**Review by duncanspumpkin — APPROVED** [review]
