### PR TITLE
Fix #1612. Ambient audio no longer playing

### LINKED ISSUE #1612: Ambient music no longer plays
**Version information:**
 - Platform: Win11
 - Version: 22.06.1
 - Build/commit: master

**Describe the bug**
Ambient sounds no longer are audible, such as birds chirping in forested areas.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load any map with empty areas
2. Go to the empty areas and hear nothing

**Expected behaviour**
Ambient sounds to play

**Screenshots**

**Additional context**

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Mistake made when refactoring to reduce global usage and didn't end up
actually setting the variable. This removes all of the loco global usage
and replaces it with a normal global. This could be further worked on in future.

### CODE REVIEW

File: src/OpenLoco/Audio/Audio.cpp [hunk 1]
```diff
@@ -914,28 +915,34 @@ namespace OpenLoco::Audio
...
+                newAmbientSound = PathId::css4;
             }
         }
         auto* channel = getChannel(ChannelId::ambient);
         if (channel == nullptr)
         {
             return;
         }
+
+        // TODO: Consider changing this so that we ask if the channel is playing a certain
```
Comment (duncanspumpkin) [inline src/OpenLoco/Audio/Audio.cpp:935]: @ZehMatt / @LeftofZen  not sure what both of you were planning on doing with audio but it might be useful to be able to check if a channel is playing a certain buffer that would avoid the requirement for ambient noise to store in an extra global what source is playing.

Comment (LeftofZen) [reply src/OpenLoco/Audio/Audio.cpp:935]: I was planning on adding some gui sliders in music options for the different channel volumes, but the channels are kinda all over the place atm so I am thinking of writing some kind of 'ChannelManager' class that bundles them together and ease of use. Could easily add a helper function in that class to do the buffer check you want

**Review by LeftofZen — APPROVED** [review]
playtested and confirmed the change works, I can now hear ambient sounds again! removing the loco_global is also a nice addition

File: src/OpenLoco/Audio/Audio.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/OpenLoco/Audio/Audio.cpp:935]: No plans at the moment
