### PR TITLE
Fix #519 Industry Window Viewport showing wrong location.

### LINKED ISSUE #519: Industry Window Viewports show incorrect location
**OS:**  Windows 10
**Version:**  20.05.1
**Commit/Build:**  e.g.  b20e73c

Industry Window Viewports show incorrect location. Resizing window and changing tabs corrects the issue. Viewport 'move to' button still works correctly.

**Steps to reproduce:**
1. Open New Game of Boulder Breakers
2. Click on any of the industries to open the window

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
image

### PR DESCRIPTION
**Pull request by Svelbeard**
Incorrect Window size was causing the saved view to be cleared and the viewport to be created twice.

### CODE REVIEW

File: src/openloco/windows/IndustryWindow.cpp [hunk 1]
```diff
@@ -83,8 +83,8 @@ namespace openloco::ui::windows::industry
         };
 
         static widget_t widgets[] = {
-            commonWidgets(223, 136, string_ids::title_town),
-            make_widget({ 3, 44 }, { 195, 79 }, widget_type::viewport, 1, 0xFFFFFFFE),
+            commonWidgets(223, 137, string_ids::title_town),
```
Comment (AaronVanGeffen) [inline src/openloco/windows/IndustryWindow.cpp:86]: town??

Comment (Svelbeard) [reply src/openloco/windows/IndustryWindow.cpp:86]: both town and industry windows use string_id 1359 `title_town` which I haven't renamed

Comment (AaronVanGeffen) [reply src/openloco/windows/IndustryWindow.cpp:86]: Ah, alright then.

**Comment by duncanspumpkin** [comment]
Could you change your commit message so that it says Fix #....: Description of fix. That way it auto closes the #... When merged
