### PR TITLE
Fix delete key not working in text input

### LINKED ISSUE #1254: Delete key does not work
**Version information:**
 - Platform: Fedora 33
 - Version: 21.10

**Describe the bug**
The Delete key does not work in input boxes, it instead inserts a random integer (sometimes negative).

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any input box (e.g. rename a station, train, etc.)
2. Use arrow keys to move inside the input box
3. Press Delete

**Expected behaviour**
The character immediately after the cursor is removed, as in Vanilla.

**Screenshots**
Delete pressed 10 times, 10 random integers inserted, starting with -24,570.
image

### PR DESCRIPTION
**Pull request by LeftofZen**
Fixes #1254, #1387

### CODE REVIEW

File: src/OpenLoco/Ui/TextInput.cpp [hunk 1]
```diff
@@ -13,7 +13,7 @@ namespace OpenLoco::Ui::TextInput
     // Common code from 0x0044685C, 0x004CE910
     bool InputSession::handleInput(uint32_t charCode, uint32_t keyCode)
     {
-        if ((charCode >= SDLK_SPACE && charCode < SDLK_F12) || (charCode >= 159 && charCode <= 255))
+        if ((charCode >= SDLK_SPACE && charCode < SDLK_DELETE) || (charCode >= 159 && charCode <= 255))
```
Comment (LeftofZen) [inline src/OpenLoco/Ui/TextInput.cpp:16]: It's coincidence that the new correct value here is 127, aka DEL in ascii, as 127 marks the end of the regular valid ascii range of values. Previously this && caught literally every key since `SDLK_F12` is a huge value, and hence always tried to append things to the buffer. Now the range is correct.

**Review by duncanspumpkin — APPROVED** [review]
