### PR TITLE
Fix #2705. Scaffolding display fail

### LINKED ISSUE #2705: Scaffolding displaying incorrectly when offices are nearing completion
**Version information:**
 - Platform: Windows 10
 - Version: 24.10
 - Build/commit: 52acc01f

**Describe the bug**
When these buildings are at their final stages of construction, OpenLoco renders the scaffolding incorrectly.
"Office Block", "Office Tower" (behind office block in first screenshot), "Offices". Other buildings not tested.

**To Reproduce**
Scenario was Aerophobia.
Save file (created in OpenLoco 24.10): [save file with the building under construction.zip](https://github.com/user-attachments/files/17686322/save.file.with.the.building.under.construction.zip)

**Screenshots**
OpenLoco 24.10:
ImageImage

Original Locomotion (Steam) for comparison:
ImageImage

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Woops made this mistake whilst implementing as i didn't test with larger buildings.

### CODE REVIEW

File: src/OpenLoco/src/Paint/PaintBuilding.cpp [hunk 1]
```diff
@@ -73,7 +73,7 @@ namespace OpenLoco::Paint
             }
             ImageId scaffImage = baseScaffImage.withIndexOffset(scaffImages.back);
             auto segmentImageOffset = imageOffset;
-            for (int8_t remainingHeight = totalSectionHeight; remainingHeight > 0; remainingHeight -= segmentHeight, segmentImageOffset.z += segmentHeight)
+            for (int16_t remainingHeight = totalSectionHeight; remainingHeight > 0; remainingHeight -= segmentHeight, segmentImageOffset.z += segmentHeight)
```
Comment (ZehMatt) [inline src/OpenLoco/src/Paint/PaintBuilding.cpp:76]: Wouldn't it be better to use coord_t? If we ever raise limits we don't want to run around all code really.

**Review by ZehMatt — APPROVED** [review]
