### PR TITLE
Fix game crash when deleting a vehicle followed on the main viewport

### LINKED ISSUE #2817: Game crashes when vehicle selected for camera to follow is deleted
**Version information:**
 - Platform: Windows build (via Linux x64 with WINE compatibility layer)
 - Version:  24.12 
 - Build/commit: master

**Describe the bug**
See title. When a vehicle is being followed by the camera, if it is deleted the camera bugs out, then the game crashes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open a scenario
2. Create a vehicle
3. Click on vehicle to get tracking window
4. Press the center on vehicle button in the bottom right of the tracking window, select "Follow vehicle on main view"
5. Delete vehicle

**Expected behaviour**
Camera defaults back to basic behaviour

**Screenshots**
N/A?, can be added if needed

**Additional context**
Likely due to the camera not being notified of the vehicle deletion, causing it to try and render from an unusable context.

### PR DESCRIPTION
**Pull request by LeftofZen**
fixes #2817

### CODE REVIEW

File: src/OpenLoco/src/Ui/Windows/Vehicle.cpp [hunk 1]
```diff
@@ -4974,6 +4974,9 @@ namespace OpenLoco::Ui::Windows::Vehicle
                 return;
             }
 
+            auto main = WindowManager::getMainWindow();
+            main->viewportUnfocusFromEntity();
```
Comment (ZehMatt) [inline src/OpenLoco/src/Ui/Windows/Vehicle.cpp]: Wouldn't this also remove focus even when its not the vehicle followed?

Comment (LeftofZen) [reply src/OpenLoco/src/Ui/Windows/Vehicle.cpp]: It would; should I change it so it just unfollows if that specific vehicle is being tracked?

Comment (LeftofZen) [reply src/OpenLoco/src/Ui/Windows/Vehicle.cpp]: @ZehMatt updated to ensure the viewport only unfollows if its following the deleted/picked up vehicle

**Review by ZehMatt — APPROVED** [review]

File: src/OpenLoco/src/Ui/Window.cpp [hunk 2]
```diff
@@ -672,14 +672,14 @@ namespace OpenLoco::Ui
         viewportConfigurations[0].viewportTargetSprite = targetEntity;
     }
 
-    bool Window::viewportIsFocusedOnEntity() const
+    bool Window::viewportIsFocusedOnEntity(EntityId targetEntity) const
     {
-        if (viewports[0] == nullptr || savedView.isEmpty())
+        if (targetEntity == EntityId::null || viewports[0] == nullptr || savedView.isEmpty())
```
Comment (ZehMatt) [inline src/OpenLoco/src/Ui/Window.cpp:677]: Looking at this code again, I think there is a mistake with this logic. targetEntity defaults to EntityId::null so this will now always return false when no entity id is provided via the parameter.

Comment (LeftofZen) [reply src/OpenLoco/src/Ui/Window.cpp:677]: Hmm I think you're right, I'll take a look tomorrow, unless you want to submit a pr to fix it sooner

Comment (LeftofZen) [reply src/OpenLoco/src/Ui/Window.cpp:677]: https://github.com/OpenLoco/OpenLoco/pull/3122
