### PR TITLE
Fix getting a refund for removing bridges owned by towns

### LINKED ISSUE #3268: Can make money by selling bridges of towns
**Version information:**
Introduced in v25.08

**To Reproduce**
1. Go to Boulder Breakers
2. Right-click on one of the existing road bridges
3. Click the bulldoze button on the road construction window
4. Profit

**Expected behaviour**
Bridges owned by towns should have zero cost to bulldoze.

### PR DESCRIPTION
**Pull request by ethan-xd**
Fixes #3268

Checks that the road is not town owned before adding on the refund for the bridge.

### CODE REVIEW

File: src/OpenLoco/src/GameCommands/Road/RemoveRoad.cpp [hunk 1]
```diff
@@ -291,8 +293,8 @@ namespace OpenLoco::GameCommands
         // 0x00477A10
         totalRemovalCost += pieceRemovalCost;
 
-        // Seems to have been forgotten in vanilla
-        if (removeRoadBridge)
+        // Add on bridge refund if applicable
```
Comment (duncanspumpkin) [inline src/OpenLoco/src/GameCommands/Road/RemoveRoad.cpp]: It is probably still useful to know that this wasn't in vanilla.

**Comment by duncanspumpkin** [comment]
Will require a changelog entry

**Review by duncanspumpkin — APPROVED** [review]
