### PR TITLE
Fix #1232: Update viewports after rendering current dirty regions

### LINKED ISSUE #1232: Screen Artifacting
**Version information:**
 - Platform: Windows 10
 - Version: 21.10
 - Build/commit: 3bec790

**Describe the bug**
When moving my overhead camera while a dropdown menu is open, portions of the menu persist for a short time over the terrain

**To Reproduce**
Steps to reproduce the behaviour:
1. Begin playing a game
2. Hover over any dropdown menu (have not noticed it with build/status windows, just dropdowns)
3. Pan the camera around the map 
4. Periodically, a piece of the menu will persist behind

**Expected behaviour**
Expected the camera to pan with no persistence

**Screenshots**
image
image

Honestly, it looks like something to do with the logic of drawing whats on the screen. If this appears over a tree farm, for example, when a tree grows/gets chopped down underneath where the dropdown artifact was, it clears the artifact from the screen.

### PR DESCRIPTION
**Pull request by ZehMatt**
This is also how its done in OpenRCT2

### CODE REVIEW

File: src/OpenLoco/src/Ui/Window.cpp [hunk 1]
```diff
@@ -278,7 +278,6 @@ namespace OpenLoco::Ui
             {
                 continue;
             }
-            this->callOnResize();
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Ui/Window.cpp:281]: I can see why the call to `updateViewports` was removed from `Ui.cpp`, but not why this `callOnResize` was removed. Could you elaborate?

**Review by AaronVanGeffen — APPROVED** [review]
Confirmed fixed! Really nice to see this resolved :+1:
