### PR TITLE
Fix #538. Prevent crashes when trying to access bad directories

### LINKED ISSUE #538: Game silently ends process when browsing for C: drive (NVMe one)
**OS:**  Windows 7 x64
**Version:**  20.05.1
**Commit/Build:**  0d6dc5e & many before

OpenLoco might crash if you browse for savegame/scenario/landscape on the C: letter/System/NVMe volume.
The rest of the drives are SATA and USB 3.0 flash memory.

**Steps to reproduce:**
1. Open the game.
2. Load a savegame/scenario/landscape on C: drive or NVMe volume.

**Is the issue reproducible in Locomotion (vanilla)?**
No

**Screenshots / Video:**
https://www.youtube.com/watch?v=2yb_5B4dn4E

**Crash dump:**
https://dbree.org/v/5f09f3

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Fix #538. Prevent crashes when trying to access bad directories

It also prevents a crash when trying to check if a file is a directory.

### CODE REVIEW

**Comment by IntelOrca** [comment]
This will prevent exceptions getting thrown on `is_directory`. We don't really want it to print errors when the user is just browsing the directory.

```
std::error_code ec;
auto isDirectory = fs::is_directory(f, ec);
```

**Comment by duncanspumpkin** [comment]
We shouldn't be throwing exceptions on is_directory though. We have already got the file/directory handle checking it again if it is a directory was throwing an exception. By changing it to .is_directory instead of the free function prevented the additional exceptions. This will now catch the exceptions on creating a directory iterator.

File: src/openloco/windows/promptbrowsewnd.cpp [hunk 1]
```diff
@@ -639,20 +640,31 @@ namespace openloco::ui::prompt_browse
...
+                try
                 {
-                    bool isDirectory = fs::is_directory(f);
-                    if (!isDirectory)
+                    for (auto& f : fs::directory_iterator(directory))
                     {
-                        auto extension = f.path().extension().u8string();
-                        if (!utility::iequals(extension, filterExtension))
+                        auto isDirectory = f.is_directory();
+                        if (f.is_symlink())
```
Comment (duncanspumpkin) [inline src/openloco/windows/promptbrowsewnd.cpp:648]: remove this was just a test but doesn't work.

**Comment by IntelOrca** [comment]
@duncanspumpkin not I understand much of what you said. `is_directory` throws an exception when called on `hiberfil.sys`, `pagefile.sys`, and `swapfile.sys`. We don't want the exception thrown, we just want to skip the file or assume it isn't a directory.

**Comment by duncanspumpkin** [comment]
The try catch is stop exceptions from trying to access directories like my documents that exist only virtually. is_directory member function does not throw on the .sys files unlike the is_directory free function.

File: src/openloco/windows/promptbrowsewnd.cpp [hunk 2]
```diff
@@ -639,20 +640,27 @@ namespace openloco::ui::prompt_browse
...
-                for (auto& f : fs::directory_iterator(directory))
+                try
                 {
-                    bool isDirectory = fs::is_directory(f);
-                    if (!isDirectory)
+                    for (auto& f : fs::directory_iterator(directory))
                     {
-                        auto extension = f.path().extension().u8string();
-                        if (!utility::iequals(extension, filterExtension))
+                        auto isDirectory = f.is_directory();
```
Comment (AaronVanGeffen) [inline src/openloco/windows/promptbrowsewnd.cpp:647]: Why was this changed from bool to auto? (Perhaps a leftover from earlier debugging?)

I suggest we change it back:
```suggestion
                        bool isDirectory = f.is_directory();
```

Comment (duncanspumpkin) [reply src/openloco/windows/promptbrowsewnd.cpp:647]: I see you're not an almost always auto person. Sure I'll change it back. I was also thinking we should actually if else check it is a file as there is a bit in-between from files to folders.

Comment (AaronVanGeffen) [reply src/openloco/windows/promptbrowsewnd.cpp:647]: Yeah, I like the use of `auto` for template-heavy types, but dislike it for primitive types.

I wouldn't mind the checks be changed as you suggest. To what extent are symlinks transparent to `is_directory` and `is_file`, though? I would prefer we keep supporting them.

Comment (duncanspumpkin) [reply src/openloco/windows/promptbrowsewnd.cpp:647]: I'm not too sure how well it currently works. I'd have to run some tests. Technically there is also sockets and other. Symlinks, hard links and junctions all could have different interactions that cause issues.

Comment (IntelOrca) [reply src/openloco/windows/promptbrowsewnd.cpp:647]: > I see you're not an almost always auto person

I am an always auto person. Always using auto where you can is just a simpler rule than deciding on a case by case basis. That said I never argue style choices like this as I believe it should just be up to the developer of that bit of code.

Comment (duncanspumpkin) [reply src/openloco/windows/promptbrowsewnd.cpp]: I've now rejigged it so that it adds it to the list only if it is a directory or a regular file. I checked to see what happens with symlinks. They get listed just like a regular directory from my testing.

Comment (AaronVanGeffen) [reply src/openloco/windows/promptbrowsewnd.cpp]: I'd like to test it on Linux, but I imagine it behaves similarly.

**Comment by AaronVanGeffen** [comment]
I wonder if this could potentially resolve #390. I can't confirm that myself, though.
