### PR TITLE
Remove globals from scenario index

### LINKED ISSUE #2797: Single player scenario scores reset after creating new scenario
**Version information:**
 - Platform: Windows 10
 - Version: 24.11
 - Build/commit: 767aa94e

**Bug description**
Creating a new scenario using the scenario editor, it wipes out all the wins from the "select scenario for new game" window.

**To Reproduce**
Steps to reproduce the behaviour:
1. On the main menu, go to "Start new game", and check which scenarios were completed
2. Go to "Scenario Editor"
3. Advance through the options, there's no need to change the default names.
4. Save the scenario
5. The game sends you back to the main menu automatically. Go to "Start new game", and all the checkmarks and scores are gone.

**Expected behaviour**
It should be possible to still see which scenarios were completed.

**Screenshots**
Image
Image
Image
Image
Image
Image
Image

### PR DESCRIPTION
**Pull request by duncanspumpkin**
A little bit of rework so should test this a little make sure i haven't broken anything.

Fix #2797

### CODE REVIEW

File: src/OpenLoco/src/ScenarioManager.cpp [hunk 1]
```diff
@@ -145,8 +142,8 @@ namespace OpenLoco::ScenarioManager
             return;
         }
 
-        stream.write(reinterpret_cast<const char*>(&*_scenarioHeader), sizeof(ScoreHeader));
-        stream.write(reinterpret_cast<const char*>(&_scenarioList[0]), sizeof(ScenarioIndexEntry) * _scenarioHeader->numScenarios);
+        stream.write(reinterpret_cast<const char*>(&_scenarioHeader), sizeof(ScoreHeader));
```
Comment (ZehMatt) [inline src/OpenLoco/src/ScenarioManager.cpp:144]: Stream has writeValue, use that instead.

File: src/OpenLoco/src/ScenarioManager.cpp [hunk 2]
```diff
@@ -145,8 +142,8 @@ namespace OpenLoco::ScenarioManager
...
+        stream.write(reinterpret_cast<const char*>(_scenarioList.data()), sizeof(ScenarioIndexEntry) * _scenarioHeader.numScenarios);
```
Comment (ZehMatt) [inline src/OpenLoco/src/ScenarioManager.cpp]: You don't need to cast, it has `const void*`

File: src/OpenLoco/src/ScenarioManager.cpp [hunk 3]
```diff
@@ -115,9 +113,8 @@ namespace OpenLoco::ScenarioManager
     ScenarioIndexEntry* getNthScenarioFromCategory(uint8_t category, uint8_t index)
     {
         uint8_t j = 0;
-        for (uint32_t i = 0; i < _scenarioHeader->numScenarios; i++)
+        for (auto& entry : _scenarioList)
```
Comment (ZehMatt) [inline src/OpenLoco/src/ScenarioManager.cpp:114]:
```suggestion
        for (const auto& entry : _scenarioList)
```

File: src/OpenLoco/src/ScenarioManager.cpp [hunk 4]
```diff
@@ -425,10 +405,9 @@ namespace OpenLoco::ScenarioManager
         const auto oldFlags = SceneManager::getSceneFlags();
         SceneManager::setSceneFlags(SceneManager::Flags::title | oldFlags);
 
-        if (_scenarioList != reinterpret_cast<ScenarioIndexEntry*>(-1) && _scenarioList != nullptr)
+        if (!_scenarioList.empty())
```
Comment (ZehMatt) [inline src/OpenLoco/src/ScenarioManager.cpp]: This is pointless to test.

File: src/OpenLoco/src/ScenarioManager.cpp (hunk 1 above)
Comment (duncanspumpkin) [reply src/OpenLoco/src/ScenarioManager.cpp:144]: sure if this was using the FileStream but it isn't at present.

File: src/OpenLoco/src/ScenarioManager.cpp (hunk 3 above)
Comment (duncanspumpkin) [reply src/OpenLoco/src/ScenarioManager.cpp:114]: need mutable entry for return

**Comment by duncanspumpkin** [comment]
Okay think this works now

File: src/OpenLoco/src/ScenarioManager.cpp [hunk 5]
```diff
@@ -405,13 +392,10 @@ namespace OpenLoco::ScenarioManager
...
-        if (!_scenarioList.empty())
-        {
-            _scenarioList.clear();
-        }
-
         const auto currentState = getCurrentScenarioFolderState();
-        if (forceReload || !tryLoadIndex(currentState))
+        // We should always try and load as we want to keep scores
+        // when adding/removing scenarios
+        if (!tryLoadIndex(currentState) || forceReload)
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/ScenarioManager.cpp:398]: Does this mean the bug with disappearing scores is fixed? That'd be worth a changelog entry.

Comment (duncanspumpkin) [reply src/OpenLoco/src/ScenarioManager.cpp:398]: yes probably

File: src/OpenLoco/src/ScenarioManager.cpp (hunk 1 above)
Comment (ZehMatt) [reply src/OpenLoco/src/ScenarioManager.cpp:144]: Oh, I didn't see that, I was certain we replaced all of the std stream stuff already.

File: src/OpenLoco/src/ScenarioManager.cpp (hunk 5 above)
Comment (duncanspumpkin) [reply src/OpenLoco/src/ScenarioManager.cpp:398]: done
