### PR TITLE
Fix #766: Performance index is off by a factor of 10

### LINKED ISSUE #766: Performance index off in scenario options window
**Version information:**
 - Platform: Arch Linux
 - Version: 20.10+
 - Build/commit: 0ee80c5d2ab7b29ef0e7149efe0df3a916ace118

**Describe the bug**
In the scenario options window, the selected performance index is off by a factor of 10.

**Screenshots**
Slika_zaslona_s_2021-02-16_22-25-03

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
We were just missing a multiplication factor. Verified that the original game was doing something similar in the equivalent prepareDraw event.

### CODE REVIEW

File: src/OpenLoco/Windows/ScenarioOptions.cpp [hunk 1]
```diff
@@ -453,7 +454,7 @@ namespace OpenLoco::Ui::Windows::ScenarioOptions
                     break;
 
                 case Scenario::objective_type::performance_index:
-                    *(int16_t*)&*commonFormatArgs = *objectivePerformanceIndex;
+                    *(int16_t*)&*commonFormatArgs = *objectivePerformanceIndex * 10;
```
Comment (duncanspumpkin) [inline src/OpenLoco/Windows/ScenarioOptions.cpp:457]: Could you take this opportunity to use format arguments

Comment (AaronVanGeffen) [reply src/OpenLoco/Windows/ScenarioOptions.cpp:457]: I considered that, but there's 16 references to `commonFormatArgs` in the file (excluding the loco_global). It seemed a little out of scope for a bugfix PR. Agreed it should be done soon, though.

**Review by duncanspumpkin — APPROVED** [review]
