### PR TITLE
Close #1030: Guard exploratory tile loops

### LINKED ISSUE #1030: Mistake in countSurroundingWaterTiles?
**Version information:**
 - Platform: Linux
 - Version: 21.05+
 - Build/commit: e9fd958b2383bb2ea9d43909c17afe195731862c

**Describe the bug**
```
* thread #1, name = 'openloco', stop reason = signal SIGABRT
  * frame #0: 0xf7fcb549 [vdso]`__kernel_vsyscall + 9
    frame #1: 0xf78b86e8 libc.so.6`raise + 200
    frame #2: 0xf78a1407 libc.so.6`abort + 290
    frame #3: 0xf7be091c libstdc++.so.6`__gnu_cxx::__verbose_terminate_handler() (.cold) at vterminate.cc:95:10
    frame #4: 0xf7bee627 libstdc++.so.6`__cxxabiv1::__terminate(void (*)()) at eh_terminate.cc:48:15
    frame #5: 0xf7bee6b3 libstdc++.so.6`std::terminate() at eh_terminate.cc:58:15
    frame #6: 0xf7bee9e5 libstdc++.so.6`__cxxabiv1::__cxa_throw(obj=0x02efb2d0, tinfo=0xf7d70f94, dest=(libstdc++.so.6`std::out_of_range::~out_of_range() at stdexcept.cc:65:3))(void *)) at eh_throw.cc:95:18
    frame #7: 0x011cfa90 openloco`OpenLoco::Interop::loco_global<OpenLoco::Map::TileElement* [196612], 14942516u>::operator[](this=0x0144bb9c, idx=-5) at Interop.hpp:319:17
    frame #8: 0x011cda87 openloco`OpenLoco::Map::TileManager::get(pos=(x = -5, y = 212))32>) at TileManager.cpp:73:33
    frame #9: 0x011cef55 openloco`OpenLoco::Map::TileManager::countSurroundingWaterTiles(pos=0xffffd138)1> const&) at TileManager.cpp:564:32
    frame #10: 0x011cf36f openloco`operator(__closure=0x00000000, regs=0x0144b9d4) at TileManager.cpp:626:53
    frame #11: 0x011cf3c2 openloco`_FUN((null)=0x0144b9d4) at TileManager.cpp:628:13
    frame #12: 0xf7fa1cd1
```

### PR DESCRIPTION
**Pull request by AaronVanGeffen**
Our implementation is more sensitive with respect to memory space. This change ensures we don't trigger any alarm bells for going outside the valid coordinate space.

### CODE REVIEW

File: src/OpenLoco/Map/TileManager.cpp [hunk 1]
```diff
@@ -561,7 +561,11 @@ namespace OpenLoco::Map::TileManager
         {
             for (uint8_t xOffset = 0; xOffset < 11; xOffset++)
             {
-                auto tile = get(initialTilePos + Map::TilePos2(xOffset, yOffset));
+                auto tilePos = initialTilePos + Map::TilePos2(xOffset, yOffset);
+                if (tilePos.x < 0 || tilePos.y < 0)
```
Comment (duncanspumpkin) [inline src/OpenLoco/Map/TileManager.cpp:565]: Should also check the max range. Tbh should make a function for validating it will need to use it in lots of places

**Review by duncanspumpkin — APPROVED** [review]

File: src/OpenLoco/Map/Map.hpp [hunk 2]
```diff
@@ -26,4 +26,25 @@ namespace OpenLoco::Map
...
+        return coord >= 0 && coord < map_columns;
+    }
+
+    constexpr bool validTileCoord(coord_t coord)
+    {
+        return coord >= 0 && coord < map_width;
+    }
+
+    template<typename TType>
+    constexpr bool validCoords(TType coords)
```
Comment (duncanspumpkin) [inline src/OpenLoco/Map/Map.hpp:41]: Oh should make this const &
