### PR TITLE
Readd config check for gridlines

### LINKED ISSUE #2412: Gridlines on landscape are toggled with the land window
**Version information:**
 - Platform: Win11
 - Version: 24.04
 - Build/commit: master/tag

**Describe the bug**
If you have "Gridlines on Landscape" enabled in the game options, then gridlines will be drawn. If you open any of the "adjust land", "build rail", "build road" or "build airport" windows in game and then close it, the gridlines will stop being rendered. When the window is opened again, the gridlines are rendered again.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable "Gridlines on Landscape" in game options
2. In a game, open the "Adjust land" window (or any of the other mentioned windows)
3. Close the window
4. Gridlines are not rendered
5. Re-open window - gridlines are rendered again

**Expected behaviour**
Gridlines are rendered regardless of window state

**Screenshots**
Option enabled
image
Window opened
image
Window closed
image

**Additional context**
The common aspect of these 4 windows is they give the user a landscape cursor. When the window exits, that cursor is removed, and that is the action I believe that is removing the gridlines.

Issue is not present in 24.01.1
Issue first appears in 24.02

### PR DESCRIPTION
**Pull request by LeftofZen**
Fixes #2412

### CODE REVIEW

File: src/OpenLoco/src/Windows/Main.cpp [hunk 1]
```diff
@@ -72,12 +72,15 @@ namespace OpenLoco::Ui::Windows::Main
     // 0x00468FFE
     void hideGridlines()
     {
-        auto window = WindowManager::getMainWindow();
-        if (window == nullptr || !window->viewports[0]->hasFlags(ViewportFlags::gridlines_on_landscape))
-            return;
+        if (!Config::get().hasFlags(Config::Flags::gridlinesOnLandscape))
+        {
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Windows/Main.cpp:76]: I'd prefer an early return over wrapping the code in an if block tbh. What do you think? It's not a big deal either way.

**Review by AaronVanGeffen — APPROVED** [review]
