### PR TITLE
Label reused imageId flag

### LINKED ISSUE #1454: Some buttons don't render their image when company colour scheme is set to pink
**Version information:**
 - Platform: Win11
 - Version: e.g. 22.03.1
 - Build/commit: latest master

**Describe the bug**
Some image buttons don't render:
image

This only happens when company colour scheme is set to pink (the last one in the list of colours)

**To Reproduce**
Steps to reproduce the behaviour:
1. Set company colour scheme to pink (last colour in the palette)
2. Build vehicle, open 'Vehicle Details' window
3. Observe the 'modify' vehicle button doesn't render it's image.

**Expected behaviour**
Button renders image as per other buttons

**Screenshots**

**Additional context**
Duncan has a fix specifically for the build vehicles window here: #1453 
But any window that is drawn by `Widget::sub_4CADE8` (most widgets) and has a colour set will need to be looked at in-game to see if this bug happens to that widget.

### PR DESCRIPTION
**Pull request by duncanspumpkin**
Close #1454

### CODE REVIEW

File: src/OpenLoco/Widget.cpp [hunk 1]
```diff
@@ -1000,7 +1000,7 @@ namespace OpenLoco::Ui
             {
                 Gfx::drawImage(ctx, pos.x, pos.y + 1, imageId);
             }
-            Gfx::drawImage(ctx, pos.x, pos.y, (1 << 30) | (51 << 19) | ImageIds::tab);
+            Gfx::drawImage(ctx, pos.x, pos.y, Widget::imageIdColourSet | (51 << 19) | ImageIds::tab);
```
Comment (duncanspumpkin) [inline src/OpenLoco/Widget.cpp:1003]: Ummm what??? Something odd here. It must be removed...

**Review by LeftofZen — APPROVED** [review]
