### PR TITLE
fix title music playing in scenario editor

### LINKED ISSUE #1680: Title music contines playing in scenario editor
**Version information:**
 - Platform: macOS
 - Version: 22.10
 - Build/commit: 30d9730

**Describe the bug**
The title music continues playing after opening the scenario editor from the title screen.

**Expected behaviour**
The music stops playing.

### PR DESCRIPTION
**Pull request by LeftofZen**
fixes #1680

### CODE REVIEW

File: src/OpenLoco/Audio/Audio.cpp [hunk 1]
```diff
@@ -1132,20 +1132,12 @@ namespace OpenLoco::Audio
...
     {
-        static PathId currentTrackPathId;
-
         auto* channel = getChannel(ChannelId::music);
         if (!_audioInitialised || _audioIsPaused || !_audioIsEnabled || channel == nullptr)
         {
             return false;
         }
 
-        if (currentTrackPathId == sample)
```
Comment (LeftofZen) [inline src/OpenLoco/Audio/Audio.cpp:1143]: this was the core problem - going into the scenario editor didn't clear this variable, so when re-entering the title screen, the value hadn't changed, and thus this method returned without ever playing the music

File: src/OpenLoco/Windows/TitleMenu.cpp [hunk 2]
```diff
@@ -327,6 +328,7 @@ namespace OpenLoco::Ui::Windows::TitleMenu
                 sub_4391E2();
                 break;
             case Widx::scenario_editor_btn:
+                Title::stop();
```
Comment (LeftofZen) [inline src/OpenLoco/Windows/TitleMenu.cpp:331]: this fixes the issue

File: src/OpenLoco/Windows/Options.cpp [hunk 3]
```diff
@@ -856,7 +856,7 @@ namespace OpenLoco::Ui::Windows::Options
 
             if (cfg.audio.playTitleMusic)
             {
-                Audio::playMusic(Environment::PathId::css5, -500, true);
+                Audio::playMusic(Environment::PathId::css5, Config::get().volume, true);
```
Comment (LeftofZen) [inline src/OpenLoco/Windows/Options.cpp:859]: this didn't change anything, i just noticed it was wrong and should be reading the config volume

**Review by duncanspumpkin — APPROVED** [review]
