### PR TITLE
Fix browse prompt text encoding issues with non-ASCII filename characters

### LINKED ISSUE #3355: Cannot load or save over saves with non-ASCII characters
**Describe the bug**
When clicking on a save that has non-ASCII characters in its filename in the load or save browse prompt, non-ASCII characters such as "ä" will get 'mojibake'd in the process of copying their file name. This causes the load operation to fail, and the save operation to create a new save with a garbled name instead of overwriting the clicked on save.

**To Reproduce**
1. Create a saved game with a file name containing at least one non-ASCII character, e.g. "Test ß.SV5"

Load method:

2. From the main menu, try to load this save.
3. The game crashes with an exception. Notice in the error message that it was trying to load e.g. "Test ÃŸ.SV5" instead of "Test ß.SV5".

Save method:

2. While playing a scenario, open the save prompt.
3. Click on a save with such a filename.
4. Notice that it does not ask if you want to overwrite it. Instead, it creates a new save with a garbled name.

**Screenshots**
Result of repeating the 'save method' described above: "A test ß.SV5" → "A test ÃŸ.SV5" → "A test ÃƒÅ¸.SV5" → "A test ÃƒÆ’Ã…Â¸.SV5" etc.
Image

**Additional context**
https://github.com/OpenLoco/OpenLoco/blob/f8020e8a96a46371bfde1cbaba81a60cf37e6e87/src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp#L271
The issue happens here. `entry.stem()`, which is of type `path`, gets converted to a u8string, which causes non-ASCII characters to get garbled.

Suggestion: This could be solved by passing `entry.stem()` to `processFileForLoadSave()` directly instead of converting it from and back to a path object via `inputSession.buffer`.

### PR DESCRIPTION
**Pull request by LeeSpork**
Fixes #3355

### CODE REVIEW

**Review by duncanspumpkin — APPROVED** [review]

File: src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp [hunk 1]
```diff
@@ -137,7 +138,7 @@ namespace OpenLoco::Ui::Windows::PromptBrowse
         Utility::strlcpy(_filter, filter, std::size(_filter));
 
         changeDirectory(directory.make_preferred());
-        inputSession = Ui::TextInput::InputSession(baseName, 200);
+        inputSession = Ui::TextInput::InputSession(OpenLoco::Localisation::convertUnicodeToLoco(baseName), 200);
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp]: Can we store this as a local first?

File: src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp [hunk 2]
```diff
@@ -906,7 +909,8 @@ namespace OpenLoco::Ui::Windows::PromptBrowse
             {
                 // Copy directory and filename to buffer.
                 char* buffer_2039 = const_cast<char*>(StringManager::getString(StringIds::buffer_2039));
-                strncpy(&buffer_2039[0], inputSession.buffer.c_str(), 512);
+                auto lococode_filename = OpenLoco::Localisation::convertUnicodeToLoco(path.stem().make_preferred().u8string());
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp]: Can we store this as a local first? (Without `OpenLoco::` qualifier as well)

File: src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp [hunk 3]
```diff
@@ -966,7 +970,8 @@ namespace OpenLoco::Ui::Windows::PromptBrowse
 
         // Copy directory and filename to buffer.
         char* buffer_2039 = const_cast<char*>(StringManager::getString(StringIds::buffer_2039));
-        strncpy(&buffer_2039[0], entry.stem().u8string().c_str(), 512);
+        auto lococode_filename = OpenLoco::Localisation::convertUnicodeToLoco(path.stem().make_preferred().u8string());
```
Comment (AaronVanGeffen) [inline src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp]: Can we store this as a local first? (Without `OpenLoco::` qualifier as well)

File: src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp (hunk 1 above)
Comment (LeeSpork) [reply src/OpenLoco/src/Ui/Windows/PromptBrowseWindow.cpp]: :+1: I have replaced `baseName` with `baseNameUtf8` and `baseNameLoco`, I hope that is good

**Review by AaronVanGeffen — COMMENTED** [review]
This feels like a patch that shouldn't be necessary, in that we should really be using UTF-8 strings internally, rather than the weird ISO 8859-1 dialect Locomotion uses.

I can see why it's necessary now, though, and what problem it's solving. Let's just go with this for now.
